#IMPORTING DATA

In [58]:
import numpy as np
import pandas as pd

In [7]:
pd.read_csv('file.csv')

,1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00
0,4.0,5.0,6.0
1,7.0,8.0,9.0

In [8]:
pd.read_table('file.csv')

  1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00
0  4.000000000000000000e+00,5.000000000000000000e...
1  7.000000000000000000e+00,8.000000000000000000e...

In [16]:
!pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\users\adity\appdata\roaming\python\python313\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\adity\appdata\roaming\python\python313\site-packages (from openpyxl) (2.0.0)

In [17]:
pd.read_excel('SIH_PS_2024.xlsx')

,Statement_id,Title,Category,Technology_Bucket,Datasetfile,Description,Department,Organisation
0,SIH1524,Innovating for Sustainability: Driving Smart R...,Hardware,Smart Resource Conservation,NaN,Innovating for Sustainability: Driving Smart R...,Godrej Appliances,Godrej Appliances
1,SIH1525,Innovating for Sustainability: Driving Smart R...,Software,Smart Resource Conservation,NaN,Innovating for Sustainability: Driving Smart R...,Godrej Appliances,Godrej Appliances
2,SIH1526,Student Innovation,Hardware,Smart Education,NaN,"Smart Education, a Concept that Describes lear...",AICTE,"AICTE, MIC-Student Innovation"
3,SIH1527,Student Innovation,Hardware,Disaster Management,NaN,Disaster Management includes ideas related to ...,AICTE,"AICTE, MIC-Student Innovation"
4,SIH1528,Student Innovation,Hardware,Miscellaneous,NaN,Technology ideas in tertiary sectors like Hosp...,AICTE,"AICTE, MIC-Student Innovation"
...,...,...,...,...,...,...,...,...
241,SIH1778,Innovative Gerontological Care Solutions: Desi...,Hardware,MedTech / BioTech / HealthTech,NaN,Develop innovative products or solutions that ...,National Council for Vocational Education and ...,Ministry of Skill Development and Entrepreneur...
242,SIH1779,Voice-Controlled Gaming Tools for Enhanced Lea...,Software,Toys & Games,NaN,Develop voice-controlled gaming tools that enh...,National Council for Vocational Education and ...,Ministry of Skill Development and Entrepreneur...
243,SIH1780,Designing Innovative Products for Empowering t...,Hardware,Smart Education,NaN,Develop innovative products or solutions that ...,National Council for Vocational Education and ...,Ministry of Skill Development and Entrepreneur...
244,SIH1781,AI-Enhanced Career Guidance System for Persona...,Software,Smart Education,NaN,Develop an AI-powered career guidance system t...,National Council for Vocational Education and ...,Ministry of Skill Development and Entrepreneur...
245,SIH1782,An online system to automatically verify new t...,Software,Miscellaneous,https://drive.google.com/drive/folders/13p8Z_X...,Background: Press Registrar General of India (...,Ministry of Information and Broadcasting,Ministry of Information and Broadcasting

In [19]:
import sqlite3

In [21]:
connection = sqlite3.connect("Sample-SQL-File-10-Rows")

In [22]:
tables = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", connection)
print(tables)

Empty DataFrame
Columns: [name]
Index: []

In [23]:
connection.close()

In [33]:
df = pd.read_json("Iris.json")  # file you downloaded
print(df.head())

   sepalLength  sepalWidth  petalLength  petalWidth species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa

In [42]:
!pip install lxml
!pip install html5lib
!pip install beautifulsoup4

import pandas as pd

# Use the HTML file you downloaded
dfs = pd.read_html("table-download.html")

print(f"Found {len(dfs)} table(s) in the file.")
print(dfs[0].head())  # show first table

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: lxml in c:\users\adity\appdata\roaming\python\python313\site-packages (6.0.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: html5lib in c:\users\adity\appdata\roaming\python\python313\site-packages (1.1)
Requirement already satisfied: six>=1.9 in c:\users\adity\appdata\roaming\python\python313\site-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in c:\users\adity\appdata\roaming\python\python313\site-packages (from html5lib) (0.5.1)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: beautifulsoup4 in c:\users\adity\appdata\roaming\python\python313\site-packages (4.13.4)
Requirement already satisfied: soupsieve>1.2 in c:\users\adity\appdata\roaming\python\python313\site-packages (from beautifulsoup4) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\adity\appdata\roaming\python\python313\site-packages (from beautifulsoup4) (4.14.1)
Found 1 table(s) in the file.
          Band Year formed  No. of Albums  \
0    Buzzcocks        1976              9
1    The Clash        1976              6
2   The Damned        1976             10
3  Sex Pistols        1975              1
4      Sham 69        1976             13

                                    Most famous song
0  Ever fallen in love (with someone you shouldn'...
1                                     London Calling
2                                        Smash it up
3                                  Anarchy in the UK
4                             If the kids are united

In [44]:
df=pd.read_clipboard()
print(df)

       Name,Age,City
0  Aditya,22,Solapur
1    Srushti,21,Pune
2     Viha,23,Mumbai

In [45]:
data = {
    "Name": ["Aditya", "Srushti", "Viha"],
    "Age": [22, 21, 23],
    "City": ["Solapur", "Pune", "Mumbai"]
}

In [49]:
df = pd.DataFrame(data)
print(df)

      Name  Age     City
0   Aditya   22  Solapur
1  Srushti   21     Pune
2     Viha   23   Mumbai

#EXPORTING DATA

In [50]:
data = {
    "Name": ["Aditya", "Srushti", "Viha"],
    "Age": [22, 21, 23],
    "City": ["Solapur", "Pune", "Mumbai"]
}
df = pd.DataFrame(data)

# Write to CSV
df.to_csv("file.csv", index=False)

In [51]:
# Write to Excel
df.to_excel("SIH_PS_2024.xlsx", index=False)

In [52]:
import sqlite3

# Connect to database
conn = sqlite3.connect("sample.db")

# Write DataFrame to SQL table
df.to_sql("Sample_SQL_Table", conn, if_exists="replace", index=False)

# Close connection
conn.close()

In [53]:
# Write to JSON
df.to_json("iris.json", orient="records", lines=True)

In [54]:
# Write to HTML
df.to_html("table-download.html", index=False)

In [55]:
# Copy DataFrame to clipboard
df.to_clipboard(index=False)

#CREATE TEST OBJECTS

In [59]:
df = pd.DataFrame(np.random.rand(20, 5))
df

           0         1         2         3         4
0   0.919768  0.000594  0.650869  0.257259  0.231741
1   0.768275  0.730086  0.226790  0.384422  0.042314
2   0.664875  0.148958  0.391220  0.973790  0.099228
3   0.322757  0.487093  0.594561  0.243943  0.067931
4   0.861647  0.892633  0.220500  0.226308  0.887641
5   0.958841  0.283663  0.744451  0.835016  0.313415
6   0.016411  0.252649  0.527520  0.652554  0.419867
7   0.442242  0.103213  0.664798  0.442236  0.762549
8   0.673655  0.429965  0.013090  0.213262  0.402056
9   0.332733  0.546526  0.082386  0.836217  0.914702
10  0.074733  0.730039  0.182226  0.871051  0.606085
11  0.958782  0.813035  0.628017  0.355797  0.967798
12  0.780510  0.169371  0.614068  0.669489  0.908794
13  0.406698  0.197392  0.468869  0.869800  0.324148
14  0.543616  0.252916  0.255357  0.038930  0.762696
15  0.396444  0.910516  0.635079  0.310388  0.500212
16  0.570310  0.433688  0.497446  0.157547  0.858227
17  0.204686  0.951620  0.159349  0.368108  0.949191
18  0.701880  0.916036  0.839459  0.338394  0.880185
19  0.325353  0.887406  0.912377  0.764464  0.067300

In [60]:
my_list = [10, 20, 30, 40, 50]  
series = pd.Series(my_list)
series

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [61]:
df.index = pd.date_range('1900/1/30', periods=df.shape[0])
df

                   0         1         2         3         4
1900-01-30  0.919768  0.000594  0.650869  0.257259  0.231741
1900-01-31  0.768275  0.730086  0.226790  0.384422  0.042314
1900-02-01  0.664875  0.148958  0.391220  0.973790  0.099228
1900-02-02  0.322757  0.487093  0.594561  0.243943  0.067931
1900-02-03  0.861647  0.892633  0.220500  0.226308  0.887641
1900-02-04  0.958841  0.283663  0.744451  0.835016  0.313415
1900-02-05  0.016411  0.252649  0.527520  0.652554  0.419867
1900-02-06  0.442242  0.103213  0.664798  0.442236  0.762549
1900-02-07  0.673655  0.429965  0.013090  0.213262  0.402056
1900-02-08  0.332733  0.546526  0.082386  0.836217  0.914702
1900-02-09  0.074733  0.730039  0.182226  0.871051  0.606085
1900-02-10  0.958782  0.813035  0.628017  0.355797  0.967798
1900-02-11  0.780510  0.169371  0.614068  0.669489  0.908794
1900-02-12  0.406698  0.197392  0.468869  0.869800  0.324148
1900-02-13  0.543616  0.252916  0.255357  0.038930  0.762696
1900-02-14  0.396444  0.910516  0.635079  0.310388  0.500212
1900-02-15  0.570310  0.433688  0.497446  0.157547  0.858227
1900-02-16  0.204686  0.951620  0.159349  0.368108  0.949191
1900-02-17  0.701880  0.916036  0.839459  0.338394  0.880185
1900-02-18  0.325353  0.887406  0.912377  0.764464  0.067300

#VIEWING/INSPECTING DATA

In [62]:
n = 5  
df.head(n)

                   0         1         2         3         4
1900-01-30  0.919768  0.000594  0.650869  0.257259  0.231741
1900-01-31  0.768275  0.730086  0.226790  0.384422  0.042314
1900-02-01  0.664875  0.148958  0.391220  0.973790  0.099228
1900-02-02  0.322757  0.487093  0.594561  0.243943  0.067931
1900-02-03  0.861647  0.892633  0.220500  0.226308  0.887641

In [63]:
n = 5  
df.tail(n)

                   0         1         2         3         4
1900-02-14  0.396444  0.910516  0.635079  0.310388  0.500212
1900-02-15  0.570310  0.433688  0.497446  0.157547  0.858227
1900-02-16  0.204686  0.951620  0.159349  0.368108  0.949191
1900-02-17  0.701880  0.916036  0.839459  0.338394  0.880185
1900-02-18  0.325353  0.887406  0.912377  0.764464  0.067300

In [64]:
df.shape

(20, 5)

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 20 entries, 1900-01-30 to 1900-02-18
Freq: D
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       20 non-null     float64
 1   1       20 non-null     float64
 2   2       20 non-null     float64
 3   3       20 non-null     float64
 4   4       20 non-null     float64
dtypes: float64(5)
memory usage: 960.0 bytes

In [66]:
df.describe()

               0          1          2          3          4
count  20.000000  20.000000  20.000000  20.000000  20.000000
mean    0.546211   0.506870   0.465422   0.490449   0.548304
std     0.286125   0.321538   0.259790   0.287707   0.338968
min     0.016411   0.000594   0.013090   0.038930   0.042314
25%     0.330888   0.238835   0.225218   0.253930   0.292997
50%     0.556963   0.460390   0.512483   0.376265   0.553149
75%     0.771334   0.831628   0.639026   0.782102   0.882049
max     0.958841   0.951620   0.912377   0.973790   0.967798

In [67]:
s = pd.Series([1, 2, 2, 3, None, 1, 2]) 
s.value_counts(dropna=False)

2.0    3
1.0    2
3.0    1
NaN    1
Name: count, dtype: int64

In [68]:
df.apply(pd.Series.value_counts)

            0    1    2    3    4
0.000594  NaN  1.0  NaN  NaN  NaN
0.013090  NaN  NaN  1.0  NaN  NaN
0.016411  1.0  NaN  NaN  NaN  NaN
0.038930  NaN  NaN  NaN  1.0  NaN
0.042314  NaN  NaN  NaN  NaN  1.0
...       ...  ...  ...  ...  ...
0.951620  NaN  1.0  NaN  NaN  NaN
0.958782  1.0  NaN  NaN  NaN  NaN
0.958841  1.0  NaN  NaN  NaN  NaN
0.967798  NaN  NaN  NaN  NaN  1.0
0.973790  NaN  NaN  NaN  1.0  NaN

[100 rows x 5 columns]

#SELECTION

In [74]:
df[0]

1900-01-30    0.919768
1900-01-31    0.768275
1900-02-01    0.664875
1900-02-02    0.322757
1900-02-03    0.861647
1900-02-04    0.958841
1900-02-05    0.016411
1900-02-06    0.442242
1900-02-07    0.673655
1900-02-08    0.332733
1900-02-09    0.074733
1900-02-10    0.958782
1900-02-11    0.780510
1900-02-12    0.406698
1900-02-13    0.543616
1900-02-14    0.396444
1900-02-15    0.570310
1900-02-16    0.204686
1900-02-17    0.701880
1900-02-18    0.325353
Freq: D, Name: 0, dtype: float64

In [73]:
df[[0, 1]]

                   0         1
1900-01-30  0.919768  0.000594
1900-01-31  0.768275  0.730086
1900-02-01  0.664875  0.148958
1900-02-02  0.322757  0.487093
1900-02-03  0.861647  0.892633
1900-02-04  0.958841  0.283663
1900-02-05  0.016411  0.252649
1900-02-06  0.442242  0.103213
1900-02-07  0.673655  0.429965
1900-02-08  0.332733  0.546526
1900-02-09  0.074733  0.730039
1900-02-10  0.958782  0.813035
1900-02-11  0.780510  0.169371
1900-02-12  0.406698  0.197392
1900-02-13  0.543616  0.252916
1900-02-14  0.396444  0.910516
1900-02-15  0.570310  0.433688
1900-02-16  0.204686  0.951620
1900-02-17  0.701880  0.916036
1900-02-18  0.325353  0.887406

In [75]:
s.iloc[0]

np.float64(1.0)

In [76]:
s.loc[0]

np.float64(1.0)

In [77]:
df.iloc[0, :]

0    0.919768
1    0.000594
2    0.650869
3    0.257259
4    0.231741
Name: 1900-01-30 00:00:00, dtype: float64

In [78]:
df.iloc[0, 0]

np.float64(0.9197676852912187)

#DATA CLEANING

In [81]:
df.columns = ['a', 'b', 'c', 'd', 'e']

In [82]:
pd.isnull(df)

                a      b      c      d      e
1900-01-30  False  False  False  False  False
1900-01-31  False  False  False  False  False
1900-02-01  False  False  False  False  False
1900-02-02  False  False  False  False  False
1900-02-03  False  False  False  False  False
1900-02-04  False  False  False  False  False
1900-02-05  False  False  False  False  False
1900-02-06  False  False  False  False  False
1900-02-07  False  False  False  False  False
1900-02-08  False  False  False  False  False
1900-02-09  False  False  False  False  False
1900-02-10  False  False  False  False  False
1900-02-11  False  False  False  False  False
1900-02-12  False  False  False  False  False
1900-02-13  False  False  False  False  False
1900-02-14  False  False  False  False  False
1900-02-15  False  False  False  False  False
1900-02-16  False  False  False  False  False
1900-02-17  False  False  False  False  False
1900-02-18  False  False  False  False  False

In [83]:
pd.notnull(df)

               a     b     c     d     e
1900-01-30  True  True  True  True  True
1900-01-31  True  True  True  True  True
1900-02-01  True  True  True  True  True
1900-02-02  True  True  True  True  True
1900-02-03  True  True  True  True  True
1900-02-04  True  True  True  True  True
1900-02-05  True  True  True  True  True
1900-02-06  True  True  True  True  True
1900-02-07  True  True  True  True  True
1900-02-08  True  True  True  True  True
1900-02-09  True  True  True  True  True
1900-02-10  True  True  True  True  True
1900-02-11  True  True  True  True  True
1900-02-12  True  True  True  True  True
1900-02-13  True  True  True  True  True
1900-02-14  True  True  True  True  True
1900-02-15  True  True  True  True  True
1900-02-16  True  True  True  True  True
1900-02-17  True  True  True  True  True
1900-02-18  True  True  True  True  True

In [84]:
df.dropna()

                   a         b         c         d         e
1900-01-30  0.919768  0.000594  0.650869  0.257259  0.231741
1900-01-31  0.768275  0.730086  0.226790  0.384422  0.042314
1900-02-01  0.664875  0.148958  0.391220  0.973790  0.099228
1900-02-02  0.322757  0.487093  0.594561  0.243943  0.067931
1900-02-03  0.861647  0.892633  0.220500  0.226308  0.887641
1900-02-04  0.958841  0.283663  0.744451  0.835016  0.313415
1900-02-05  0.016411  0.252649  0.527520  0.652554  0.419867
1900-02-06  0.442242  0.103213  0.664798  0.442236  0.762549
1900-02-07  0.673655  0.429965  0.013090  0.213262  0.402056
1900-02-08  0.332733  0.546526  0.082386  0.836217  0.914702
1900-02-09  0.074733  0.730039  0.182226  0.871051  0.606085
1900-02-10  0.958782  0.813035  0.628017  0.355797  0.967798
1900-02-11  0.780510  0.169371  0.614068  0.669489  0.908794
1900-02-12  0.406698  0.197392  0.468869  0.869800  0.324148
1900-02-13  0.543616  0.252916  0.255357  0.038930  0.762696
1900-02-14  0.396444  0.910516  0.635079  0.310388  0.500212
1900-02-15  0.570310  0.433688  0.497446  0.157547  0.858227
1900-02-16  0.204686  0.951620  0.159349  0.368108  0.949191
1900-02-17  0.701880  0.916036  0.839459  0.338394  0.880185
1900-02-18  0.325353  0.887406  0.912377  0.764464  0.067300

In [85]:
df.dropna(axis=1)

                   a         b         c         d         e
1900-01-30  0.919768  0.000594  0.650869  0.257259  0.231741
1900-01-31  0.768275  0.730086  0.226790  0.384422  0.042314
1900-02-01  0.664875  0.148958  0.391220  0.973790  0.099228
1900-02-02  0.322757  0.487093  0.594561  0.243943  0.067931
1900-02-03  0.861647  0.892633  0.220500  0.226308  0.887641
1900-02-04  0.958841  0.283663  0.744451  0.835016  0.313415
1900-02-05  0.016411  0.252649  0.527520  0.652554  0.419867
1900-02-06  0.442242  0.103213  0.664798  0.442236  0.762549
1900-02-07  0.673655  0.429965  0.013090  0.213262  0.402056
1900-02-08  0.332733  0.546526  0.082386  0.836217  0.914702
1900-02-09  0.074733  0.730039  0.182226  0.871051  0.606085
1900-02-10  0.958782  0.813035  0.628017  0.355797  0.967798
1900-02-11  0.780510  0.169371  0.614068  0.669489  0.908794
1900-02-12  0.406698  0.197392  0.468869  0.869800  0.324148
1900-02-13  0.543616  0.252916  0.255357  0.038930  0.762696
1900-02-14  0.396444  0.910516  0.635079  0.310388  0.500212
1900-02-15  0.570310  0.433688  0.497446  0.157547  0.858227
1900-02-16  0.204686  0.951620  0.159349  0.368108  0.949191
1900-02-17  0.701880  0.916036  0.839459  0.338394  0.880185
1900-02-18  0.325353  0.887406  0.912377  0.764464  0.067300

In [86]:
df.dropna(thresh=3)

                   a         b         c         d         e
1900-01-30  0.919768  0.000594  0.650869  0.257259  0.231741
1900-01-31  0.768275  0.730086  0.226790  0.384422  0.042314
1900-02-01  0.664875  0.148958  0.391220  0.973790  0.099228
1900-02-02  0.322757  0.487093  0.594561  0.243943  0.067931
1900-02-03  0.861647  0.892633  0.220500  0.226308  0.887641
1900-02-04  0.958841  0.283663  0.744451  0.835016  0.313415
1900-02-05  0.016411  0.252649  0.527520  0.652554  0.419867
1900-02-06  0.442242  0.103213  0.664798  0.442236  0.762549
1900-02-07  0.673655  0.429965  0.013090  0.213262  0.402056
1900-02-08  0.332733  0.546526  0.082386  0.836217  0.914702
1900-02-09  0.074733  0.730039  0.182226  0.871051  0.606085
1900-02-10  0.958782  0.813035  0.628017  0.355797  0.967798
1900-02-11  0.780510  0.169371  0.614068  0.669489  0.908794
1900-02-12  0.406698  0.197392  0.468869  0.869800  0.324148
1900-02-13  0.543616  0.252916  0.255357  0.038930  0.762696
1900-02-14  0.396444  0.910516  0.635079  0.310388  0.500212
1900-02-15  0.570310  0.433688  0.497446  0.157547  0.858227
1900-02-16  0.204686  0.951620  0.159349  0.368108  0.949191
1900-02-17  0.701880  0.916036  0.839459  0.338394  0.880185
1900-02-18  0.325353  0.887406  0.912377  0.764464  0.067300

In [87]:
df.fillna(0)

                   a         b         c         d         e
1900-01-30  0.919768  0.000594  0.650869  0.257259  0.231741
1900-01-31  0.768275  0.730086  0.226790  0.384422  0.042314
1900-02-01  0.664875  0.148958  0.391220  0.973790  0.099228
1900-02-02  0.322757  0.487093  0.594561  0.243943  0.067931
1900-02-03  0.861647  0.892633  0.220500  0.226308  0.887641
1900-02-04  0.958841  0.283663  0.744451  0.835016  0.313415
1900-02-05  0.016411  0.252649  0.527520  0.652554  0.419867
1900-02-06  0.442242  0.103213  0.664798  0.442236  0.762549
1900-02-07  0.673655  0.429965  0.013090  0.213262  0.402056
1900-02-08  0.332733  0.546526  0.082386  0.836217  0.914702
1900-02-09  0.074733  0.730039  0.182226  0.871051  0.606085
1900-02-10  0.958782  0.813035  0.628017  0.355797  0.967798
1900-02-11  0.780510  0.169371  0.614068  0.669489  0.908794
1900-02-12  0.406698  0.197392  0.468869  0.869800  0.324148
1900-02-13  0.543616  0.252916  0.255357  0.038930  0.762696
1900-02-14  0.396444  0.910516  0.635079  0.310388  0.500212
1900-02-15  0.570310  0.433688  0.497446  0.157547  0.858227
1900-02-16  0.204686  0.951620  0.159349  0.368108  0.949191
1900-02-17  0.701880  0.916036  0.839459  0.338394  0.880185
1900-02-18  0.325353  0.887406  0.912377  0.764464  0.067300

In [88]:
s.fillna(s.mean())

0    1.000000
1    2.000000
2    2.000000
3    3.000000
4    1.833333
5    1.000000
6    2.000000
dtype: float64

In [89]:
s.astype(float)

0    1.0
1    2.0
2    2.0
3    3.0
4    NaN
5    1.0
6    2.0
dtype: float64

In [90]:
s.replace(1, 'one')

0    one
1    2.0
2    2.0
3    3.0
4    NaN
5    one
6    2.0
dtype: object

In [91]:
s.replace([1, 3], ['one', 'three'])

0      one
1      2.0
2      2.0
3    three
4      NaN
5      one
6      2.0
dtype: object

In [92]:
df.rename(columns=lambda x: x + '_1')

                 a_1       b_1       c_1       d_1       e_1
1900-01-30  0.919768  0.000594  0.650869  0.257259  0.231741
1900-01-31  0.768275  0.730086  0.226790  0.384422  0.042314
1900-02-01  0.664875  0.148958  0.391220  0.973790  0.099228
1900-02-02  0.322757  0.487093  0.594561  0.243943  0.067931
1900-02-03  0.861647  0.892633  0.220500  0.226308  0.887641
1900-02-04  0.958841  0.283663  0.744451  0.835016  0.313415
1900-02-05  0.016411  0.252649  0.527520  0.652554  0.419867
1900-02-06  0.442242  0.103213  0.664798  0.442236  0.762549
1900-02-07  0.673655  0.429965  0.013090  0.213262  0.402056
1900-02-08  0.332733  0.546526  0.082386  0.836217  0.914702
1900-02-09  0.074733  0.730039  0.182226  0.871051  0.606085
1900-02-10  0.958782  0.813035  0.628017  0.355797  0.967798
1900-02-11  0.780510  0.169371  0.614068  0.669489  0.908794
1900-02-12  0.406698  0.197392  0.468869  0.869800  0.324148
1900-02-13  0.543616  0.252916  0.255357  0.038930  0.762696
1900-02-14  0.396444  0.910516  0.635079  0.310388  0.500212
1900-02-15  0.570310  0.433688  0.497446  0.157547  0.858227
1900-02-16  0.204686  0.951620  0.159349  0.368108  0.949191
1900-02-17  0.701880  0.916036  0.839459  0.338394  0.880185
1900-02-18  0.325353  0.887406  0.912377  0.764464  0.067300

In [93]:
df.rename(columns={'a': 'alpha'})

               alpha         b         c         d         e
1900-01-30  0.919768  0.000594  0.650869  0.257259  0.231741
1900-01-31  0.768275  0.730086  0.226790  0.384422  0.042314
1900-02-01  0.664875  0.148958  0.391220  0.973790  0.099228
1900-02-02  0.322757  0.487093  0.594561  0.243943  0.067931
1900-02-03  0.861647  0.892633  0.220500  0.226308  0.887641
1900-02-04  0.958841  0.283663  0.744451  0.835016  0.313415
1900-02-05  0.016411  0.252649  0.527520  0.652554  0.419867
1900-02-06  0.442242  0.103213  0.664798  0.442236  0.762549
1900-02-07  0.673655  0.429965  0.013090  0.213262  0.402056
1900-02-08  0.332733  0.546526  0.082386  0.836217  0.914702
1900-02-09  0.074733  0.730039  0.182226  0.871051  0.606085
1900-02-10  0.958782  0.813035  0.628017  0.355797  0.967798
1900-02-11  0.780510  0.169371  0.614068  0.669489  0.908794
1900-02-12  0.406698  0.197392  0.468869  0.869800  0.324148
1900-02-13  0.543616  0.252916  0.255357  0.038930  0.762696
1900-02-14  0.396444  0.910516  0.635079  0.310388  0.500212
1900-02-15  0.570310  0.433688  0.497446  0.157547  0.858227
1900-02-16  0.204686  0.951620  0.159349  0.368108  0.949191
1900-02-17  0.701880  0.916036  0.839459  0.338394  0.880185
1900-02-18  0.325353  0.887406  0.912377  0.764464  0.067300

In [94]:
df.set_index('a')

                 b         c         d         e
a
0.919768  0.000594  0.650869  0.257259  0.231741
0.768275  0.730086  0.226790  0.384422  0.042314
0.664875  0.148958  0.391220  0.973790  0.099228
0.322757  0.487093  0.594561  0.243943  0.067931
0.861647  0.892633  0.220500  0.226308  0.887641
0.958841  0.283663  0.744451  0.835016  0.313415
0.016411  0.252649  0.527520  0.652554  0.419867
0.442242  0.103213  0.664798  0.442236  0.762549
0.673655  0.429965  0.013090  0.213262  0.402056
0.332733  0.546526  0.082386  0.836217  0.914702
0.074733  0.730039  0.182226  0.871051  0.606085
0.958782  0.813035  0.628017  0.355797  0.967798
0.780510  0.169371  0.614068  0.669489  0.908794
0.406698  0.197392  0.468869  0.869800  0.324148
0.543616  0.252916  0.255357  0.038930  0.762696
0.396444  0.910516  0.635079  0.310388  0.500212
0.570310  0.433688  0.497446  0.157547  0.858227
0.204686  0.951620  0.159349  0.368108  0.949191
0.701880  0.916036  0.839459  0.338394  0.880185
0.325353  0.887406  0.912377  0.764464  0.067300

In [96]:
df.rename(index=lambda x: x + pd.Timedelta(days=1))

                   a         b         c         d         e
1900-01-31  0.919768  0.000594  0.650869  0.257259  0.231741
1900-02-01  0.768275  0.730086  0.226790  0.384422  0.042314
1900-02-02  0.664875  0.148958  0.391220  0.973790  0.099228
1900-02-03  0.322757  0.487093  0.594561  0.243943  0.067931
1900-02-04  0.861647  0.892633  0.220500  0.226308  0.887641
1900-02-05  0.958841  0.283663  0.744451  0.835016  0.313415
1900-02-06  0.016411  0.252649  0.527520  0.652554  0.419867
1900-02-07  0.442242  0.103213  0.664798  0.442236  0.762549
1900-02-08  0.673655  0.429965  0.013090  0.213262  0.402056
1900-02-09  0.332733  0.546526  0.082386  0.836217  0.914702
1900-02-10  0.074733  0.730039  0.182226  0.871051  0.606085
1900-02-11  0.958782  0.813035  0.628017  0.355797  0.967798
1900-02-12  0.780510  0.169371  0.614068  0.669489  0.908794
1900-02-13  0.406698  0.197392  0.468869  0.869800  0.324148
1900-02-14  0.543616  0.252916  0.255357  0.038930  0.762696
1900-02-15  0.396444  0.910516  0.635079  0.310388  0.500212
1900-02-16  0.570310  0.433688  0.497446  0.157547  0.858227
1900-02-17  0.204686  0.951620  0.159349  0.368108  0.949191
1900-02-18  0.701880  0.916036  0.839459  0.338394  0.880185
1900-02-19  0.325353  0.887406  0.912377  0.764464  0.067300

#FILTER, SORT, & GROUPBY

In [98]:
df[df['a'] > 0.5]

                   a         b         c         d         e
1900-01-30  0.919768  0.000594  0.650869  0.257259  0.231741
1900-01-31  0.768275  0.730086  0.226790  0.384422  0.042314
1900-02-01  0.664875  0.148958  0.391220  0.973790  0.099228
1900-02-03  0.861647  0.892633  0.220500  0.226308  0.887641
1900-02-04  0.958841  0.283663  0.744451  0.835016  0.313415
1900-02-07  0.673655  0.429965  0.013090  0.213262  0.402056
1900-02-10  0.958782  0.813035  0.628017  0.355797  0.967798
1900-02-11  0.780510  0.169371  0.614068  0.669489  0.908794
1900-02-13  0.543616  0.252916  0.255357  0.038930  0.762696
1900-02-15  0.570310  0.433688  0.497446  0.157547  0.858227
1900-02-17  0.701880  0.916036  0.839459  0.338394  0.880185

In [99]:
df[(df['a'] > 0.5) & (df['a'] < 0.7)]

                   a         b         c         d         e
1900-02-01  0.664875  0.148958  0.391220  0.973790  0.099228
1900-02-07  0.673655  0.429965  0.013090  0.213262  0.402056
1900-02-13  0.543616  0.252916  0.255357  0.038930  0.762696
1900-02-15  0.570310  0.433688  0.497446  0.157547  0.858227

In [100]:
df.sort_values('a')

                   a         b         c         d         e
1900-02-05  0.016411  0.252649  0.527520  0.652554  0.419867
1900-02-09  0.074733  0.730039  0.182226  0.871051  0.606085
1900-02-16  0.204686  0.951620  0.159349  0.368108  0.949191
1900-02-02  0.322757  0.487093  0.594561  0.243943  0.067931
1900-02-18  0.325353  0.887406  0.912377  0.764464  0.067300
1900-02-08  0.332733  0.546526  0.082386  0.836217  0.914702
1900-02-14  0.396444  0.910516  0.635079  0.310388  0.500212
1900-02-12  0.406698  0.197392  0.468869  0.869800  0.324148
1900-02-06  0.442242  0.103213  0.664798  0.442236  0.762549
1900-02-13  0.543616  0.252916  0.255357  0.038930  0.762696
1900-02-15  0.570310  0.433688  0.497446  0.157547  0.858227
1900-02-01  0.664875  0.148958  0.391220  0.973790  0.099228
1900-02-07  0.673655  0.429965  0.013090  0.213262  0.402056
1900-02-17  0.701880  0.916036  0.839459  0.338394  0.880185
1900-01-31  0.768275  0.730086  0.226790  0.384422  0.042314
1900-02-11  0.780510  0.169371  0.614068  0.669489  0.908794
1900-02-03  0.861647  0.892633  0.220500  0.226308  0.887641
1900-01-30  0.919768  0.000594  0.650869  0.257259  0.231741
1900-02-10  0.958782  0.813035  0.628017  0.355797  0.967798
1900-02-04  0.958841  0.283663  0.744451  0.835016  0.313415

In [101]:
df.sort_values('b', ascending=False)

                   a         b         c         d         e
1900-02-16  0.204686  0.951620  0.159349  0.368108  0.949191
1900-02-17  0.701880  0.916036  0.839459  0.338394  0.880185
1900-02-14  0.396444  0.910516  0.635079  0.310388  0.500212
1900-02-03  0.861647  0.892633  0.220500  0.226308  0.887641
1900-02-18  0.325353  0.887406  0.912377  0.764464  0.067300
1900-02-10  0.958782  0.813035  0.628017  0.355797  0.967798
1900-01-31  0.768275  0.730086  0.226790  0.384422  0.042314
1900-02-09  0.074733  0.730039  0.182226  0.871051  0.606085
1900-02-08  0.332733  0.546526  0.082386  0.836217  0.914702
1900-02-02  0.322757  0.487093  0.594561  0.243943  0.067931
1900-02-15  0.570310  0.433688  0.497446  0.157547  0.858227
1900-02-07  0.673655  0.429965  0.013090  0.213262  0.402056
1900-02-04  0.958841  0.283663  0.744451  0.835016  0.313415
1900-02-13  0.543616  0.252916  0.255357  0.038930  0.762696
1900-02-05  0.016411  0.252649  0.527520  0.652554  0.419867
1900-02-12  0.406698  0.197392  0.468869  0.869800  0.324148
1900-02-11  0.780510  0.169371  0.614068  0.669489  0.908794
1900-02-01  0.664875  0.148958  0.391220  0.973790  0.099228
1900-02-06  0.442242  0.103213  0.664798  0.442236  0.762549
1900-01-30  0.919768  0.000594  0.650869  0.257259  0.231741

In [102]:
df.sort_values(['a', 'b'], ascending=[True, False])

                   a         b         c         d         e
1900-02-05  0.016411  0.252649  0.527520  0.652554  0.419867
1900-02-09  0.074733  0.730039  0.182226  0.871051  0.606085
1900-02-16  0.204686  0.951620  0.159349  0.368108  0.949191
1900-02-02  0.322757  0.487093  0.594561  0.243943  0.067931
1900-02-18  0.325353  0.887406  0.912377  0.764464  0.067300
1900-02-08  0.332733  0.546526  0.082386  0.836217  0.914702
1900-02-14  0.396444  0.910516  0.635079  0.310388  0.500212
1900-02-12  0.406698  0.197392  0.468869  0.869800  0.324148
1900-02-06  0.442242  0.103213  0.664798  0.442236  0.762549
1900-02-13  0.543616  0.252916  0.255357  0.038930  0.762696
1900-02-15  0.570310  0.433688  0.497446  0.157547  0.858227
1900-02-01  0.664875  0.148958  0.391220  0.973790  0.099228
1900-02-07  0.673655  0.429965  0.013090  0.213262  0.402056
1900-02-17  0.701880  0.916036  0.839459  0.338394  0.880185
1900-01-31  0.768275  0.730086  0.226790  0.384422  0.042314
1900-02-11  0.780510  0.169371  0.614068  0.669489  0.908794
1900-02-03  0.861647  0.892633  0.220500  0.226308  0.887641
1900-01-30  0.919768  0.000594  0.650869  0.257259  0.231741
1900-02-10  0.958782  0.813035  0.628017  0.355797  0.967798
1900-02-04  0.958841  0.283663  0.744451  0.835016  0.313415

In [103]:
df.groupby('a')

In [104]:
df.groupby(['a', 'b'])

In [105]:
df.groupby('a')['b'].mean()

a
0.016411    0.252649
0.074733    0.730039
0.204686    0.951620
0.322757    0.487093
0.325353    0.887406
0.332733    0.546526
0.396444    0.910516
0.406698    0.197392
0.442242    0.103213
0.543616    0.252916
0.570310    0.433688
0.664875    0.148958
0.673655    0.429965
0.701880    0.916036
0.768275    0.730086
0.780510    0.169371
0.861647    0.892633
0.919768    0.000594
0.958782    0.813035
0.958841    0.283663
Name: b, dtype: float64

In [106]:
df.pivot_table(index='a', values=['b','c'], aggfunc='mean')

                 b         c
a
0.016411  0.252649  0.527520
0.074733  0.730039  0.182226
0.204686  0.951620  0.159349
0.322757  0.487093  0.594561
0.325353  0.887406  0.912377
0.332733  0.546526  0.082386
0.396444  0.910516  0.635079
0.406698  0.197392  0.468869
0.442242  0.103213  0.664798
0.543616  0.252916  0.255357
0.570310  0.433688  0.497446
0.664875  0.148958  0.391220
0.673655  0.429965  0.013090
0.701880  0.916036  0.839459
0.768275  0.730086  0.226790
0.780510  0.169371  0.614068
0.861647  0.892633  0.220500
0.919768  0.000594  0.650869
0.958782  0.813035  0.628017
0.958841  0.283663  0.744451

In [109]:
df.groupby('a').agg('mean')

                 b         c         d         e
a
0.016411  0.252649  0.527520  0.652554  0.419867
0.074733  0.730039  0.182226  0.871051  0.606085
0.204686  0.951620  0.159349  0.368108  0.949191
0.322757  0.487093  0.594561  0.243943  0.067931
0.325353  0.887406  0.912377  0.764464  0.067300
0.332733  0.546526  0.082386  0.836217  0.914702
0.396444  0.910516  0.635079  0.310388  0.500212
0.406698  0.197392  0.468869  0.869800  0.324148
0.442242  0.103213  0.664798  0.442236  0.762549
0.543616  0.252916  0.255357  0.038930  0.762696
0.570310  0.433688  0.497446  0.157547  0.858227
0.664875  0.148958  0.391220  0.973790  0.099228
0.673655  0.429965  0.013090  0.213262  0.402056
0.701880  0.916036  0.839459  0.338394  0.880185
0.768275  0.730086  0.226790  0.384422  0.042314
0.780510  0.169371  0.614068  0.669489  0.908794
0.861647  0.892633  0.220500  0.226308  0.887641
0.919768  0.000594  0.650869  0.257259  0.231741
0.958782  0.813035  0.628017  0.355797  0.967798
0.958841  0.283663  0.744451  0.835016  0.313415

In [110]:
df.apply(np.mean)

a    0.546211
b    0.506870
c    0.465422
d    0.490449
e    0.548304
dtype: float64

In [111]:
df.apply(np.max, axis=1)

1900-01-30    0.919768
1900-01-31    0.768275
1900-02-01    0.973790
1900-02-02    0.594561
1900-02-03    0.892633
1900-02-04    0.958841
1900-02-05    0.652554
1900-02-06    0.762549
1900-02-07    0.673655
1900-02-08    0.914702
1900-02-09    0.871051
1900-02-10    0.967798
1900-02-11    0.908794
1900-02-12    0.869800
1900-02-13    0.762696
1900-02-14    0.910516
1900-02-15    0.858227
1900-02-16    0.951620
1900-02-17    0.916036
1900-02-18    0.912377
Freq: D, dtype: float64

#JOIN/COMBINE

In [113]:
df1 = pd.DataFrame(np.random.rand(3, 3), columns=['a', 'b', 'c'])
df2 = pd.DataFrame(np.random.rand(2, 3), columns=['a', 'b', 'c'])

In [115]:
df_combined = pd.concat([df1, df2], axis=0, ignore_index=True)
df_combined

          a         b         c
0  0.655441  0.230718  0.317117
1  0.440070  0.888906  0.480419
2  0.248100  0.992548  0.307881
3  0.351406  0.757071  0.063096
4  0.213889  0.120832  0.861337

In [116]:
pd.concat([df1, df2], axis=1)

          a         b         c         a         b         c
0  0.655441  0.230718  0.317117  0.351406  0.757071  0.063096
1  0.440070  0.888906  0.480419  0.213889  0.120832  0.861337
2  0.248100  0.992548  0.307881       NaN       NaN       NaN

In [118]:
df_joined = df1.join(df2.set_index('a'), on='a', how='inner', lsuffix='_df1', rsuffix='_df2')
df_joined

Empty DataFrame
Columns: [a, b_df1, c_df1, b_df2, c_df2]
Index: []

#STATISTICS

In [119]:
df.describe()

               a          b          c          d          e
count  20.000000  20.000000  20.000000  20.000000  20.000000
mean    0.546211   0.506870   0.465422   0.490449   0.548304
std     0.286125   0.321538   0.259790   0.287707   0.338968
min     0.016411   0.000594   0.013090   0.038930   0.042314
25%     0.330888   0.238835   0.225218   0.253930   0.292997
50%     0.556963   0.460390   0.512483   0.376265   0.553149
75%     0.771334   0.831628   0.639026   0.782102   0.882049
max     0.958841   0.951620   0.912377   0.973790   0.967798

In [120]:
df.mean()

a    0.546211
b    0.506870
c    0.465422
d    0.490449
e    0.548304
dtype: float64

In [121]:
df.corr()

          a         b         c         d         e
a  1.000000 -0.136294  0.185437 -0.254228  0.042942
b -0.136294  1.000000 -0.072302 -0.181703  0.239701
c  0.185437 -0.072302  1.000000  0.086975 -0.183452
d -0.254228 -0.181703  0.086975  1.000000 -0.260817
e  0.042942  0.239701 -0.183452 -0.260817  1.000000

In [122]:
df.count()

a    20
b    20
c    20
d    20
e    20
dtype: int64

In [123]:
df.max()

a    0.958841
b    0.951620
c    0.912377
d    0.973790
e    0.967798
dtype: float64

In [124]:
df.min()

a    0.016411
b    0.000594
c    0.013090
d    0.038930
e    0.042314
dtype: float64

In [125]:
df.median()

a    0.556963
b    0.460390
c    0.512483
d    0.376265
e    0.553149
dtype: float64

In [126]:
df.std()

a    0.286125
b    0.321538
c    0.259790
d    0.287707
e    0.338968
dtype: float64